export const NAV = [
  { label: "Início", to: "/" },
  { label: "Quem Somos", to: "/quem-somos" },
  { label: "Feira de Santana", to: "/feira-de-santana" },
  { label: "Serviços", to: "/servicos" },
  { label: "Eventos", to: "/eventos" },
  { label: "Notícias", to: "/noticias" },
  { label: "Contato", to: "/contato" },
] as const;

export const SERVICES = [
  {
    slug: "juceb",
    title: "JUCEB · Junta Comercial",
    short: "Serviços da Junta Comercial do Estado da Bahia.",
    desc: "A ACEFS, através da Junta Comercial do Estado da Bahia, oferece uma diversidade de serviços essenciais para associados, empreendedores e empresas de Feira e região.",
    icon: "building",
  },
  {
    slug: "scpc",
    title: "Consultas e Negativações",
    short: "Análise de crédito e proteção contra inadimplência.",
    desc: "Através da Equifax Boa Vista, a ACEFS disponibiliza uma variedade de serviços, incluindo análise de crédito, gestão de risco, auxiliando na concessão de créditos e prevenção de fraudes.",
    icon: "shield",
  },
  {
    slug: "certificado-digital",
    title: "Certificado Digital",
    short: "Emissão de e-CPF e e-CNPJ com atendimento ágil.",
    desc: "Emissão presencial ou na sua empresa. Validade jurídica reconhecida e agilidade para obrigações fiscais.",
    icon: "certificate",
  },
  {
    slug: "assistencia-saude",
    title: "Assistência à Saúde",
    short: "Planos de saúde e odontológicos para associados.",
    desc: "Uma excelente opção para empresas que desejam um benefício com custo reduzido, restrito aos seus diretores e colaboradores, extensivo a dependentes.",
    icon: "health",
  },
  {
    slug: "auditorios",
    title: "Auditórios para Eventos",
    short: "Espaços climatizados para treinamentos e conferências.",
    desc: "Auditórios climatizados e equipados, específicos para receber grupos para apresentações, palestras e conferências corporativas.",
    icon: "auditorium",
  },
  {
    slug: "palestras",
    title: "Palestras & Workshops",
    short: "Capacitação técnica e motivacional em parceria com o Sebrae.",
    desc: "Em parceria com o Sebrae, universidades e outras entidades empresariais, a ACEFS realiza diversos eventos técnicos, motivacionais e workshops.",
    icon: "presentation",
  },
  {
    slug: "credito",
    title: "Acesso a Crédito",
    short: "Apoio na busca por linhas de crédito e financiamento.",
    desc: "Junto com instituições financeiras e cooperativas de crédito parceiras, a ACEFS auxilia o empresário na busca por apoio financeiro.",
    icon: "credit",
  },
  {
    slug: "cursos",
    title: "Cursos & Capacitação",
    short: "Formação contínua para empresários e equipes.",
    desc: "Programas em gestão, vendas, finanças e liderança, desenvolvidos em parceria com o Sebrae.",
    icon: "book",
  },
  {
    slug: "networking",
    title: "Networking & Eventos",
    short: "Conexões entre lideranças e representação institucional.",
    desc: "Encontros, rodadas de negócios e articulação junto ao poder público em defesa do empresariado local.",
    icon: "network",
  },
  {
    slug: "radio",
    title: "Programa de Rádio",
    short: "\"Negócios & Conexões\" — todo domingo, na Sociedade News FM.",
    desc: "Programa semanal apresentado por Genildo Melo e Danillo Freitas, com entrevistas e debates sobre empreendedorismo e o ambiente de negócios de Feira de Santana.",
    icon: "radio",
  },
  {
    slug: "mediacao",
    title: "Mediação e Arbitragem",
    short: "Resolução de conflitos empresariais fora do judiciário.",
    desc: "Câmara de mediação e arbitragem para resolução ágil e técnica de conflitos entre empresas associadas.",
    icon: "scale",
  },
] as const;

export const EVENTS = [
  {
    slug: "3a-colorrida",
    title: "3ª Colorrida — em prol do combate ao câncer infantil",
    date: "06 de agosto de 2026",
    time: "19h30",
    location: "Auditório da ACEFS — Largo São Francisco, 43, Kalilândia, Feira de Santana",
    desc: "Lançamento oficial 2026. Vem participar de um passeio colorido que ajuda a construir a nova sede da AAPC, ampliando o acolhimento e o cuidado a pessoas em tratamento contra o câncer. A Colorrida é muito mais que uma corrida — é um movimento de solidariedade, esperança e amor ao próximo. Sua presença faz toda a diferença.",
    hasArt: true,
  },
  {
    slug: "cafe-empresarial-acefs",
    title: "Café Empresarial ACEFS",
    date: "Mensal",
    time: "8h",
    location: "Sede da ACEFS",
    desc: "Encontro mensal de networking entre associados, com pauta aberta sobre o cenário econômico e as demandas do comércio local.",
    hasArt: false,
  },
  {
    slug: "premio-fama",
    title: "Prêmio Fama",
    date: "11 de setembro de 2026",
    time: "A confirmar",
    location: "A confirmar",
    desc: "Premiação que reconhece empresas e profissionais de destaque no comércio de Feira de Santana. Detalhes e inscrições em breve.",
    hasArt: false,
  },
  {
    slug: "caminhada-ame-se",
    title: "Caminhada Ame-se — Setembro Amarelo",
    date: "13 de setembro de 2026",
    time: "A confirmar",
    location: "A confirmar",
    desc: "Ação de conscientização sobre saúde mental e valorização da vida, em apoio à campanha Setembro Amarelo.",
    hasArt: false,
  },
] as const;

export const NEWS = [
  {
    slug: "acefs-reune-liderancas-varejo",
    category: "Encontro",
    date: "12 Jun 2026",
    title: "ACEFS reúne lideranças para debater o futuro do varejo regional",
    excerpt: "Mais de 200 empresários no auditório discutiram crédito, logística urbana e digitalização do comércio.",
  },
  {
    slug: "cursos-gratuitos-julho",
    category: "Formação",
    date: "04 Jun 2026",
    title: "Nova rodada de cursos gratuitos para associados em julho",
    excerpt: "Inscrições abertas para capacitações em gestão financeira e marketing digital.",
  },
  {
    slug: "sebrae-acefs-consultoria",
    category: "Parceria",
    date: "28 Mai 2026",
    title: "Sebrae e ACEFS ampliam consultoria gratuita às MPEs",
    excerpt: "Atendimento semanal começa em junho na sede da associação.",
  },
  {
    slug: "assembleia-2026",
    category: "Institucional",
    date: "15 Mai 2026",
    title: "Assembleia geral aprova diretrizes para o próximo biênio",
    excerpt: "Associados definem prioridades em representação, formação e serviços digitais.",
  },
  {
    slug: "feira-negocios",
    category: "Evento",
    date: "02 Mai 2026",
    title: "Feira de Negócios ACEFS reúne 80 expositores no centro",
    excerpt: "Rodadas de compras conectaram indústrias locais a compradores de todo o Nordeste.",
  },
  {
    slug: "premio-mercado",
    category: "Reconhecimento",
    date: "22 Abr 2026",
    title: "Prêmio Mérito do Comércio homenageia 12 empresas centenárias",
    excerpt: "Cerimônia celebrou negócios que ajudaram a construir Feira de Santana.",
  },
] as const;

export const PARTNERS = [
  "CACB",
  "FACEB",
  "Sebrae Bahia",
  "Boa Vista",
  "ISO 9001",
  "Serasa Experian",
] as const;