/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as NegociosEConexoesRouteImport } from './routes/negocios-e-conexoes'
import { Route as FeiraDeSantanaRouteImport } from './routes/feira-de-santana'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as EmpregosRouteImport } from './routes/empregos'
import { Route as DiretoriaRouteImport } from './routes/diretoria'
import { Route as CurriculoRouteImport } from './routes/curriculo'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiaSlugRouteImport } from './routes/noticia.$slug'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosEConexoesRoute = NegociosEConexoesRouteImport.update({
  id: '/negocios-e-conexoes',
  path: '/negocios-e-conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FeiraDeSantanaRoute = FeiraDeSantanaRouteImport.update({
  id: '/feira-de-santana',
  path: '/feira-de-santana',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpregosRoute = EmpregosRouteImport.update({
  id: '/empregos',
  path: '/empregos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretoriaRoute = DiretoriaRouteImport.update({
  id: '/diretoria',
  path: '/diretoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculoRoute = CurriculoRouteImport.update({
  id: '/curriculo',
  path: '/curriculo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiaSlugRoute = NoticiaSlugRouteImport.update({
  id: '/noticia/$slug',
  path: '/noticia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoRoute
  '/curriculo': typeof CurriculoRoute
  '/diretoria': typeof DiretoriaRoute
  '/empregos': typeof EmpregosRoute
  '/eventos': typeof EventosRoute
  '/feira-de-santana': typeof FeiraDeSantanaRoute
  '/negocios-e-conexoes': typeof NegociosEConexoesRoute
  '/noticias': typeof NoticiasRoute
  '/parceiros': typeof ParceirosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoRoute
  '/curriculo': typeof CurriculoRoute
  '/diretoria': typeof DiretoriaRoute
  '/empregos': typeof EmpregosRoute
  '/eventos': typeof EventosRoute
  '/feira-de-santana': typeof FeiraDeSantanaRoute
  '/negocios-e-conexoes': typeof NegociosEConexoesRoute
  '/noticias': typeof NoticiasRoute
  '/parceiros': typeof ParceirosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoRoute
  '/curriculo': typeof CurriculoRoute
  '/diretoria': typeof DiretoriaRoute
  '/empregos': typeof EmpregosRoute
  '/eventos': typeof EventosRoute
  '/feira-de-santana': typeof FeiraDeSantanaRoute
  '/negocios-e-conexoes': typeof NegociosEConexoesRoute
  '/noticias': typeof NoticiasRoute
  '/parceiros': typeof ParceirosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artigos'
    | '/contato'
    | '/curriculo'
    | '/diretoria'
    | '/empregos'
    | '/eventos'
    | '/feira-de-santana'
    | '/negocios-e-conexoes'
    | '/noticias'
    | '/parceiros'
    | '/quem-somos'
    | '/servicos'
    | '/noticia/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artigos'
    | '/contato'
    | '/curriculo'
    | '/diretoria'
    | '/empregos'
    | '/eventos'
    | '/feira-de-santana'
    | '/negocios-e-conexoes'
    | '/noticias'
    | '/parceiros'
    | '/quem-somos'
    | '/servicos'
    | '/noticia/$slug'
  id:
    | '__root__'
    | '/'
    | '/artigos'
    | '/contato'
    | '/curriculo'
    | '/diretoria'
    | '/empregos'
    | '/eventos'
    | '/feira-de-santana'
    | '/negocios-e-conexoes'
    | '/noticias'
    | '/parceiros'
    | '/quem-somos'
    | '/servicos'
    | '/noticia/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigosRoute: typeof ArtigosRoute
  ContatoRoute: typeof ContatoRoute
  CurriculoRoute: typeof CurriculoRoute
  DiretoriaRoute: typeof DiretoriaRoute
  EmpregosRoute: typeof EmpregosRoute
  EventosRoute: typeof EventosRoute
  FeiraDeSantanaRoute: typeof FeiraDeSantanaRoute
  NegociosEConexoesRoute: typeof NegociosEConexoesRoute
  NoticiasRoute: typeof NoticiasRoute
  ParceirosRoute: typeof ParceirosRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ServicosRoute: typeof ServicosRoute
  NoticiaSlugRoute: typeof NoticiaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios-e-conexoes': {
      id: '/negocios-e-conexoes'
      path: '/negocios-e-conexoes'
      fullPath: '/negocios-e-conexoes'
      preLoaderRoute: typeof NegociosEConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feira-de-santana': {
      id: '/feira-de-santana'
      path: '/feira-de-santana'
      fullPath: '/feira-de-santana'
      preLoaderRoute: typeof FeiraDeSantanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empregos': {
      id: '/empregos'
      path: '/empregos'
      fullPath: '/empregos'
      preLoaderRoute: typeof EmpregosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretoria': {
      id: '/diretoria'
      path: '/diretoria'
      fullPath: '/diretoria'
      preLoaderRoute: typeof DiretoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculo': {
      id: '/curriculo'
      path: '/curriculo'
      fullPath: '/curriculo'
      preLoaderRoute: typeof CurriculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticia/$slug': {
      id: '/noticia/$slug'
      path: '/noticia/$slug'
      fullPath: '/noticia/$slug'
      preLoaderRoute: typeof NoticiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigosRoute: ArtigosRoute,
  ContatoRoute: ContatoRoute,
  CurriculoRoute: CurriculoRoute,
  DiretoriaRoute: DiretoriaRoute,
  EmpregosRoute: EmpregosRoute,
  EventosRoute: EventosRoute,
  FeiraDeSantanaRoute: FeiraDeSantanaRoute,
  NegociosEConexoesRoute: NegociosEConexoesRoute,
  NoticiasRoute: NoticiasRoute,
  ParceirosRoute: ParceirosRoute,
  QuemSomosRoute: QuemSomosRoute,
  ServicosRoute: ServicosRoute,
  NoticiaSlugRoute: NoticiaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
